/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_leon_ndk1_Store */

#ifndef _Included_com_example_leon_ndk1_Store
#define _Included_com_example_leon_ndk1_Store
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    getCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_leon_ndk1_Store_getCount
  (JNIEnv *, jobject);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_leon_ndk1_Store_getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    getInteger
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_leon_ndk1_Store_getInteger
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    getBoolean
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_leon_ndk1_Store_getBoolean
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    getColor
 * Signature: (Ljava/lang/String;)Lcom/example/leon/ndk1/Color;
 */
JNIEXPORT jobject JNICALL Java_com_example_leon_ndk1_Store_getColor
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    setString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_leon_ndk1_Store_setString
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    setInteger
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_example_leon_ndk1_Store_setInteger
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    setBoolean
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_example_leon_ndk1_Store_setBoolean
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    setColor
 * Signature: (Ljava/lang/String;Lcom/example/leon/ndk1/Color;)V
 */
JNIEXPORT void JNICALL Java_com_example_leon_ndk1_Store_setColor
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    getIntegerArray
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_leon_ndk1_Store_getIntegerArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    setIntegerArray
 * Signature: (Ljava/lang/String;[I)V
 */
JNIEXPORT void JNICALL Java_com_example_leon_ndk1_Store_setIntegerArray
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    getStringArray
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_leon_ndk1_Store_getStringArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    setStringArray
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_leon_ndk1_Store_setStringArray
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    getColorArray
 * Signature: (Ljava/lang/String;)[Lcom/example/leon/ndk1/Color;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_leon_ndk1_Store_getColorArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    setColorArray
 * Signature: (Ljava/lang/String;[Lcom/example/leon/ndk1/Color;)V
 */
JNIEXPORT void JNICALL Java_com_example_leon_ndk1_Store_setColorArray
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    startWatcher
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_leon_ndk1_Store_startWatcher
  (JNIEnv *, jobject);

/*
 * Class:     com_example_leon_ndk1_Store
 * Method:    stopWatcher
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_leon_ndk1_Store_stopWatcher
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
